### PR TITLE
Fixes the resetContentAndSettings command

### PR DESCRIPTION
**Pull request by andrejborstnik**
- [x] This is a small change #1059

---

**Description:**
Fixes `resetContentAndSettings` - no longer freezes the simulator.

### CODE REVIEW

**Comment by rotemmiz** [comment]
The current implementation would break parallelism support.

Where do you see this issue now, on Xcode 10.1?

**Comment by andrejborstnik** [comment]
@rotemmiz Yes, on Xcode 10.1. I described the problem in the issue #1059.

**Comment by LeoNatan** [comment]
This looks like a bad solution. We do not control the Simulator app, the user does. Killing it because of an Apple bug does not sound to me like a good idea.

**Comment by LeoNatan** [comment]
Closing this PR. Please open an issue with Apple at https://bugreport.apple.com

**Pull request closed without merging**
