### PR TITLE
refactor: allow technically to control multiple detox instances 

### PR DESCRIPTION
**Pull request by manuquentin**
- [x] This change has been discussed in issue #1119 and the solution has been agreed upon with maintainers.

---

Rework from #1138

### CODE REVIEW

**Comment by manuquentin** [comment]
No @stale please no :)

**Comment by noomorph** [comment]
I'll look at your pull request in this month, hopefully in mid-April.

**Comment by manuquentin** [comment]
Thanks @noomorph  !
If you want an illustration, I've made a blog post explaining our needs of testing multiple devices: http://blog.wazo.community/testing-interaction-between-mobile-applications.html#testing-interaction-between-mobile-applications

**Comment by noomorph** [comment]
@manuquentin, I've started examining your pull request and apologize that it takes a bit more time than you would probably like to wait. I'm not completely familiar with this part of codebase and would prefer to sit in a company with a debugger and to smoke my way through your code, as it is a very interesting part and actually I enjoy your direction of thought in regards to moving away from stateful modules. I skimmed your article a week and half ago, looked like a nice tutorial to me, AFAIR. 

You know, I want to ask you, if you are okay with that... to shuffle arguments a bit, across all those constructors, since the idea of invocation manager actually looks like very central for well-being of any class (`Interaction`, `Element`, whatever). Doesn't it make more sense to you to make `invocationManager` always the first arg in constuctor, as shown below?

```diff
 class WaitForActionInteraction extends Interaction {
-  constructor(element, matcher, searchMatcher, invocationManager) {
+  constructor(invocationManager, element, matcher, searchMatcher) {

...

 class Element {
-  constructor(matcher, invocationManager) {
+  constructor(invocationManager, matcher) {
```

I'm also musing in a direction of some factory for all this stuff (to address a slight redundancy), but I'm not ready to state anything firm right now - I might be wrong. I just have a gut feeling that we can still improve things a bit there. For instance, you have some private method calls (looks somewhat hacky and hurried):

```
exportWrapper._setDetoxClient(detox.client);
```

I just want you to know that I have my eyes on your pull request and I'm positive about it, in general.

Sorry for the extra legwork in advance. :) If you have objections regarding my constructor args shuffle request, please voice them here.

**Comment by manuquentin** [comment]
Hi @noomorph !
I've followed your advice and moved all `invocationManager` as first parameter of all functions.

I've tested it successfully on our project (~100 tests in 10 testsuites).

Regards,
Emmanuel

**Comment by noomorph** [comment]
@manuquentin, thank you very much! I am beginning to review your PR (the second reading, so to say). If gods are merciful to us, hope to see it merged this week.

**Comment by noomorph** [comment]
@manuquentin, I wanted to ask your permission to cherry-pick my commit (https://github.com/wix/Detox/pull/1378/commits/b2a19b3d046158c2a705ca3577813bf72f6b4864) to your fork's branch.

Before I do that, could you squash your commits into one and force push to your branch? I plan to `rebase and merge` instead of `squash and merge`, so that we both do not lose our respective authorships to the commits.

Thanks in advance!

**P.S.** As you are one of few people who have a real codebase with multiple detox instances, could you give a try to a (currently) final version with that commit? Or at least take a look at [the gist](https://gist.github.com/noomorph/06506567a25b6098c33c37349c2fb926).

**P.P.S.** If you can't process my request in the meantime, could you please tell when approximately we can return to this PR? It turned out to be not so small (with the proper restructuring of instances within classes), hence here time is not on our side - big PRs get outdated faster than smaller ones, just a fact, unfortunately.

**Comment by manuquentin** [comment]
Hi @noomorph !
Sorry for the delay, I'm in vacation right now. I'll take a look in a couple a day.

Regards

**Comment by noomorph** [comment]
@manuquentin, hehe, I suspected that (in spite of your green Github punchcard this week). Amuse-toi bien! Thank you very much for bringing in clarity!

**Comment by noomorph** [comment]
@manuquentin, is there a chance you can test the branch on your environment?

**Comment by manuquentin** [comment]
Hi @noomorph, I'm back from vacation.
I'll test it today.

**Comment by manuquentin** [comment]
@noomorph I can confirm that this branch is functional on my side 👌

**Pull request merged**
