### PR TITLE
Exchange com.fasterxml.jackson with org.json implementation

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
With this PR we get rid of the dependency towards `com.fasterxml.jackson`. The android unit tests work, unfortunately I can't compile to run the android unit E2E tests. I am a bit unsure if this is a problem with my local setup or a general problem.

### CODE REVIEW

**Comment by rotemmiz** [comment]
@DanielMSchmidt try now, I think it is fixed now.

**Comment by DanielMSchmidt** [comment]
@rotemmiz Thank you for your help! I tried again today and tried to get my setup straight, but the tests still won't run. I tested it with `master` and got the same error, so I guess it's my setup.

As CI doesn't cover android yet, could anyone check this out and report if it works 🙈

**Comment by rotemmiz** [comment]
Ping me when you want to test your setup

**Comment by rotemmiz** [comment]
👏

**Comment by DanielMSchmidt** [comment]
Hey @rotemmiz, I let the test run locally (my setup works now 👍 ) and it ran with an error, but the error seems unrelated. Would be neat to have android support in the CI pipeline....

From my point of view we could merge this.

Here is the error output:

```sh
1) Matchers :ios: should match elements by accesibility trait:
     Error: Error: 'is assignable from class: class android.view.View' matches multiple views in the hierarchy.
Problem views are marked with '****MATCHES****' below.

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#81810100 pfl=0x20000 wanim=0x10302f6 needsMenuKey=2 colorMode=0}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3} ****MATCHES****
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1776, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@9005c05, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} ****MATCHES****
|
+-->ViewStub{id=16908679, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@20ee45a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} ****MATCHES****
|
+-->FrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1704, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@649e368, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=72.0, child-count=1} ****MATCHES****
|
+--->ReactRootView{id=81, visibility=VISIBLE, width=1080, height=1704, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@62ccbac, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=12} ****MATCHES****
|
+---->ReactViewGroup{id=53, visibility=VISIBLE, width=102, height=117, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3f865bc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=489.0, y=257.0, child-count=1} ****MATCHES****
|
+----->ReactTextView{id=52, desc=Label, visibility=VISIBLE, width=102, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@b2ac945, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Label, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactViewGroup{id=56, visibility=VISIBLE, width=39, height=117, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ae8e89a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=521.0, y=374.0, child-count=1} ****MATCHES****
|
+----->ReactTextView{id=55, visibility=VISIBLE, width=39, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@d2625cb, tag=UniqueId345, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=ID, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactViewGroup{id=59, visibility=VISIBLE, width=105, height=87, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ec421a8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=488.0, y=491.0, child-count=1} ****MATCHES****
|
+----->ReactTextView{id=58, visibility=VISIBLE, width=105, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@bb3b4c1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Traits, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactViewGroup{id=62, visibility=VISIBLE, width=150, height=180, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@adcf466, tag=null, root-is-layout-requested=false, has-input-connection=false, x=465.0, y=578.0, child-count=1} ****MATCHES****
|
+----->ReactImageView{id=60, visibility=VISIBLE, width=150, height=150, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@f6f53a7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} ****MATCHES****
|
+---->ReactViewGroup{id=66, visibility=VISIBLE, width=192, height=192, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@80db054, tag=Grandfather883, root-is-layout-requested=false, has-input-connection=false, x=444.0, y=758.0, child-count=1} ****MATCHES****
|
+----->ReactViewGroup{id=65, visibility=VISIBLE, width=144, height=144, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@e85dbfd, tag=Father883, root-is-layout-requested=false, has-input-connection=false, x=24.0, y=24.0, child-count=1} ****MATCHES****
|
+------>ReactViewGroup{id=64, visibility=VISIBLE, width=96, height=96, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@ab3f0f2, tag=Son883, root-is-layout-requested=false, has-input-connection=false, x=24.0, y=24.0, child-count=1} ****MATCHES****
|
+------->ReactViewGroup{id=63, visibility=VISIBLE, width=48, height=48, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@f338343, tag=Grandson883, root-is-layout-requested=false, has-input-connection=false, x=24.0, y=24.0, child-count=0} ****MATCHES****
|
+---->ReactTextView{id=68, visibility=VISIBLE, width=148, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3bf7dc0, tag=ProductId000, root-is-layout-requested=false, has-input-connection=false, x=154.0, y=1010.0, text=Product, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactTextView{id=70, visibility=VISIBLE, width=148, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3593af9, tag=ProductId001, root-is-layout-requested=false, has-input-connection=false, x=362.0, y=1010.0, text=Product, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactTextView{id=73, visibility=VISIBLE, width=148, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@28c2a3e, tag=ProductId002, root-is-layout-requested=false, has-input-connection=false, x=570.0, y=1010.0, text=Product, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactTextView{id=75, visibility=VISIBLE, width=148, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@481109f, tag=ProductId003, root-is-layout-requested=false, has-input-connection=false, x=778.0, y=1010.0, text=Product, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactViewGroup{id=79, visibility=VISIBLE, width=101, height=117, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7feb5ec, tag=null, root-is-layout-requested=false, has-input-connection=false, x=490.0, y=1157.0, child-count=1} ****MATCHES****
|
+----->ReactTextView{id=78, visibility=VISIBLE, width=101, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@3698db5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Index, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactViewGroup{id=83, visibility=VISIBLE, width=101, height=117, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c1cac4a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=490.0, y=1274.0, child-count=1} ****MATCHES****
|
+----->ReactTextView{id=82, visibility=VISIBLE, width=101, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@ff017bb, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Index, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+---->ReactViewGroup{id=86, visibility=VISIBLE, width=101, height=117, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@61744d8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=490.0, y=1391.0, child-count=1} ****MATCHES****
|
+----->ReactTextView{id=85, visibility=VISIBLE, width=101, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@5f25031, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Index, input-type=0, ime-target=false, has-links=false} ****MATCHES****
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=144, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@5af7586, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1776.0} ****MATCHES****
|
+->View{id=16908335, res-name=statusBarBackground, visibility=VISIBLE, width=1080, height=72, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@d280e47, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} ****MATCHES****
|
```

**Comment by rotemmiz** [comment]
` Matchers :ios: should match elements by accesibility trait:`
It's an iOS test (traits do no exist on Android)

We don't have a good way to separate iOS and Android tests, I will add device.getPlatform() condition inside the test for now, to make it pass, but we need to grep (or rather invert grep) non ios tests through the command line tool

**Comment by rotemmiz** [comment]
So actually, this is how I currently run the test suite
`node_modules/.bin/mocha e2e --opts e2e/mocha.opts  --configuration android.emu.release --grep :ios: --invert --loglevel verbose`

**Comment by DanielMSchmidt** [comment]
That works better, but there is still an error:

```sh
 Error: Error: View is present in the hierarchy: ReactTextView{id=55, visibility=VISIBLE, width=39, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@5b89a27, tag=UniqueId345, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=ID, input-type=0, ime-target=false, has-links=false}
Expected: is <false>
     Got: <true>
```

**Comment by DanielMSchmidt** [comment]
@rotemmiz If it works on your machine feel free to merge and publish 👍

**Pull request merged**
