### PR TITLE
Resolve UIWindowScene _keyWindowScene unrecognized selector

### PR DESCRIPTION
**Pull request by calebmackdavenport**
## Description

Please feel free to edit anything you need to, just would like to get https://github.com/wix/Detox/issues/2895 resolved.

- This pull request addresses the issue described here: 
https://github.com/wix/Detox/issues/2895

In this pull request, I have
Resolved an iOS 15 issue:
image

Reference: https://stackoverflow.com/a/58447461/8665723 thanks to @hcwesson for the link
https://github.com/baronapp/Detox as well
and #2895 (comment) for initial solution

Working example shown below or [here](https://github.com/calebmackdavenport/Detox/tree/demo-react-native-nav)
Would love to add the example as well to improve ability to test similar issues in the future, but would prefer a quick resolution and a separate discussion for the example.

---

> _For features/enhancements:_
 - n/a

> _For API changes:_
 - n/a
 

https://user-images.githubusercontent.com/30021449/135011870-cfeb3ea3-f894-4425-99d0-a4aa2d1761ff.mov

### CODE REVIEW

**Comment by calebmackdavenport** [comment]
detox-android-64-x-pr failing at
image

 not sure if open issue

**Comment by noomorph** [comment]
@alon-ha , this PR would need some of your love and attention soon. 🙏

**Comment by calebmackdavenport** [comment]
Added a navigation sandbox to examples. Didn't want to add too much and make it difficult to maintain.
If there are suspect scenarios with nested/multiple screens, it should be easier to test now.

https://user-images.githubusercontent.com/30021449/135027263-01ba5e30-10b5-4730-bc0c-4a4ea29616d3.mov

**Comment by calebmackdavenport** [comment]
https://github.com/wix/Detox/issues/2895#issuecomment-929328796

**Comment by calebmackdavenport** [comment]
This build also working for my company's app and is able to successfully interact with screens and e2e tests pass.

https://user-images.githubusercontent.com/30021449/135152535-86b38916-03b7-437d-8cd9-989aceff72ba.mov

**Review by alon-ha — APPROVED** [review]

**Comment by alon-ha** [comment]
@calebmackdavenport  Thank you for the PR, I merged and will release a new version of detox.

**Comment by calebmackdavenport** [comment]
Yep! Thanks again @mikehardy !! Hopefully this tag works

**Pull request merged**
