### PR TITLE
Update mockito

### PR DESCRIPTION
**Pull request by codebutler**
## Description

- This pull request addresses the issue described here: #3238

In this pull request, I have …

Updated to the latest mockito.

### CODE REVIEW

**Comment by d4vidi** [comment]
@codebutler thanks. We are likely to merge this in and release soon.
Side question: Have been working on any contributions to our project?

**Comment by codebutler** [comment]
> @codebutler thanks. We are likely to merge this in and release soon. Side question: Have you been working on any contributions to Detox?

Great, thanks for the quick reply.

Yes, I'm working on a new feature that I hope to discuss merging in. It's not ready yet but see here:
https://github.com/codebutler/Detox/commit/ba434b152a46286bf6b7b48259a5bd91a5b23e57

**Comment by noomorph** [comment]
What's the status here, guys? @jonathanmos, @d4vidi ?

**Comment by d4vidi** [comment]
It is on our plate and will be followed through soon 👍🏻 #3271 was done as a preliminary action.

**Comment by d4vidi** [comment]
@codebutler pretty please 😄

**Comment by noomorph** [comment]
@d4vidi, no worries, I did that :)

**Review by d4vidi — APPROVED** [review]

**Pull request merged**
