### PR TITLE
Added testBinaryPath as an optional config parameter

### PR DESCRIPTION
**Pull request by reime005**
At a specific point in an app configuration the 'testBinaryPath' was not correct and I had the need to configure it manually. Please let me know if that does not make sense.

Tested on Android emulator, with and without the testBinaryPath parameter.

### CODE REVIEW

**Comment by chips5k** [comment]
+1 for this - my team need this feature as the conventions guessed path is completely wrong in our setup. the only work around at present is to rename and shift our files to match what its expecting...

**Comment by rotemmiz** [comment]
While the PR code is good, I have an issue with the documentation. Since it's optional, I think testBinaryPath should be removed from the introduction example.

**Comment by reime005** [comment]
sure, done

**Comment by rotemmiz** [comment]
I want to merge this but CI on this PR is still remember, can you please check?

**Comment by rotemmiz** [comment]
A unit test still fails.
`✕ installApp() with a custom app path should use custom app path`

**Comment by rotemmiz** [comment]
DTXLoggingInfra submodule has changed its reference, can you please revert that?

**Comment by rotemmiz** [comment]
There is still one conflict :(

**Comment by reime005** [comment]
> There is still one conflict :(

should be fine now

**Pull request merged**
