### PR TITLE
Upgrade ws to 3.3.1 or later

### PR DESCRIPTION
**Pull request by denissb**
This is a small change 

Old version of WS have a security vulnerability, see https://github.com/websockets/ws/commit/c4fe46608acd61fbf7397eadc47378903f95b78a

### CODE REVIEW

**Comment by LeoNatan** [comment]
@d4vidi Can you pls look at the android build log? The build failed but not sure if related to this. Thanks

**Comment by d4vidi** [comment]
Doesn't seem related to `ws`. I've rerun the broken build. In any case - better go over the breaking changes before upgrading mindlessly.

**Comment by noomorph** [comment]
@d4vidi, this is the list of the breaking changes:

> Breaking changes
> Removed the upgradeReq property - https://github.com/websockets/ws/pull/1099
> Removed unnecessary events - https://github.com/websockets/ws/pull/1100
> Removed the flags argument from the 'message', 'ping', and 'pong'
events - https://github.com/websockets/ws/pull/1101
> The permessage-deflate extension is now disabled by default on the server - https://github.com/websockets/ws/pull/1107

None of them is related to the way we use it.

**Comment by LeoNatan** [comment]
@denissb Thanks for your PR!

**Comment by denissb** [comment]
@LeoNatan and thank you for your efforts :)

**Pull request merged**
