### PR TITLE
Add support for disabling touch indicators through launch argument

### LINKED ISSUE #640: Allow to disable touch indicators on IOS
We are implementing screenshot tests when running detox, there is a issue that we have to wait 500ms just to be sure that all touch indicators have disappeared. It would be nice to have an option to disable them.

### PR DESCRIPTION
**Pull request by LeoNatan**
Closes #640

TODO: JS support

### CODE REVIEW

**Comment by LeoNatan** [comment]
@Gongreg

**Comment by LeoNatan** [comment]
Reminder @Gongreg

**Comment by LeoNatan** [comment]
@haswalt Are you still willing to help? We just need an additional input param to be passed as a launch argument for iOS.

**Comment by haswalt** [comment]
@LeoNatan Sure. I'll have a look at this tomorrow.

**Comment by LeoNatan** [comment]
Thanks!

**Comment by haswalt** [comment]
@LeoNatan Is there a relatively painless way to get my fork of detox running in a project?

**Comment by LeoNatan** [comment]
Closing in favor of #899

**Pull request closed without merging**
