### PR TITLE
Remove use of legacy notifications API [WIP]

### PR DESCRIPTION
**Pull request by LeoNatan**
Remove legacy local and remote notification API
Remove legacy RN support

React Native also dropped support for Xcode 8: facebook/react-native#18944

### CODE REVIEW

**Comment by abarisic86** [comment]
Any reason why this isn't reviewed and merged?

**Comment by LeoNatan** [comment]
Internal reasons and backlog.

Is there something specifically that is blocking you?

**Comment by Liampronan** [comment]
@LeoNatan not sure if this PR would fix this issue, but it seems like there is an issue related to Xcode 10: https://github.com/wix/Detox/issues/911#issuecomment-424621863. i may give this branch a try in a bit to see if it helps with that issue

**Comment by LeoNatan** [comment]
All issues with Xcode 10 building have been resolved, as far as I know. This branch updates the minimum version requirement of app deployment target and cleans up several uses of deprecated APIs. If implemented correctly, it should give no signs to the end user that something changed (other than require the end user to update their toolchain and their apps).

**Comment by Liampronan** [comment]
got it, thanks for clarifying, @LeoNatan! I just saw that issue and posted here cause I thought it might help with context. After going through some more issues, I was able to solve my problem, so yeah feel free to ignore above post and thank you for getting back!

**Comment by noomorph** [comment]
@LeoNatan, what's up with this branch? Anything useful that is still unmerged and we could leverage?

**Comment by LeoNatan** [comment]
The whole branch.

**Comment by LeoNatan** [comment]
Cannot be merged because of One App.

**Comment by LeoNatan** [comment]
I see now that internally, we will start using the new iOS notifications API soon. In that case, I will fix conflicts and merge once that happens.

**Comment by LeoNatan** [comment]
I'll close this and start a new one.

**Pull request closed without merging**
