### PR TITLE
Bugfix on Biometrics

### PR DESCRIPTION
**Pull request by abunsen**
**Description:**

This is a small change - I missed the "s" in `includes` on 3 methods and had an extra "m" in the anchor link on the docs.

### CODE REVIEW

**Comment by abunsen** [comment]
Not sure why it failed, is this normal? https://jenkins-oss.wixpress.com/job/detox-ios-59-8-pr/1395//console

**Comment by LeoNatan** [comment]
Thanks

**Comment by brandons** [comment]
This is such a useful new feature, great work! @LeoNatan Would you mind publishing a release with this fix?

**Comment by LeoNatan** [comment]
Out

**Pull request merged**
