### PR TITLE
Add Support for ShakeDevice Action

### PR DESCRIPTION
**Pull request by LeoNatan**
On iOS, this works by sending a Darwin notification that the simulator sends when simulating shake.

Still TODO: 
- <s>Need JS support (@rotemmiz)</s>
- Android native

This solves #551

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@LeoNatan Can you link the earl grey PR in the comment?

**Comment by LeoNatan** [comment]
It's not submitted yet 😂 I will try to finish it today. Need to understand fully their code architecture before submitting.

@DanielMSchmidt Would you like to add JS support?

**Comment by LeoNatan** [comment]
Added JS for iOS. Still need Android shake implementation.

**Comment by LeoNatan** [comment]
"Guys come on, it has been 21 days. This is very important for our customers." 😂

**Pull request merged**
