### PR TITLE
test sharding/parallelization 

### PR DESCRIPTION
**Pull request by doronpr**
+ moved e2e tests to jesr

### CODE REVIEW

**Comment by LeoNatan** [comment]
#601 is blocking this. Should be fixed first before merging this.

**Comment by doronpr** [comment]
@LeoNatan why blocker?
there's going to be a bug where PN isn't ready for parallelization but we can fix it when we get to it. No?

**Comment by LeoNatan** [comment]
I don't think that is the right approach. I think we should fix all known issues before merging this large PR. 
in the case of #601, it's a very thing to fix.

**Comment by doronpr** [comment]
closing in favour of https://github.com/wix/detox/pull/609

**Pull request closed without merging**
