### PR TITLE
Updating Guide.Mocking with Metro breaking changes

### PR DESCRIPTION
**Pull request by antonabyzov**
- [x] This change has been discussed in issue #1420 and the solution has been agreed upon with maintainers.

Updating Guide.Mocking with Metro breaking changes

### CODE REVIEW

**Comment by rotemmiz** [comment]
Can you please add the corresponding react native version that uses metro 0.43?

**Comment by LeoNatan** [comment]
@rotemmiz Can we merge this?

**Comment by heroic** [comment]
This doesn't work for me.

Here's my metro.config.js

```
const defaultSourceExts = require('metro-config/src/defaults/defaults').sourceExts
module.exports = {
  resolver: { 
    sourceExts: process.env.RN_SRC_EXT
      ? process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts)
      : defaultSourceExts,
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
}
```

I'm starting metro with `RN_SRC_EXT=e2e.js yarn start` and running detox with `RN_SRC_EXT=e2e.js yarn build:android && RN_SRC_EXT=e2e.js yarn test:android`

I have a file `api.e2e.js` and `api.js` in the same directory and yet, api.js is being used. As per the docs, it should be picking up api.e2e.js

**Comment by antonabyzov** [comment]
Do you have api.js and api.e2e.js side by side (e.g. in the same folder)?

**Comment by heroic** [comment]
I was able to get it to work after restarting my laptop.

**Comment by LeoNatan** [comment]
Thanks for this PR.

**Pull request merged**
