### PR TITLE
Detox Next (iOS, Phase 1)

### PR DESCRIPTION
**Pull request by LeoNatan**
First phase of Detox Next for iOS. This focuses on replacing Earl Grey's actions, matchers and expectations with our own custom ones. The entire invocation system has been replaced.

Implementing this, we've taken into account several requests from the community, such as `getAttributes()` for elements, `.not`, the ability to disable synchronization on launch and tidying up the APIs.

Still TODO:

- [x] ~https://github.com/wix/Detox/issues/2089~
- [x] ~https://github.com/wix/Detox/issues/2069~
- [ ] https://github.com/wix/Detox/issues/2108

### CODE REVIEW

**Comment by LeoNatan** [comment]
Still TODO:

https://github.com/wix/Detox/issues/2089
https://github.com/wix/Detox/issues/2069

**Comment by LeoNatan** [comment]
Android builds are broken. 😓 @rotemmiz

**Comment by LeoNatan** [comment]
@rotemmiz There are still attempts at generation or some silly testing of it:

```
00:34:05 lerna ERR! /Users/jenkins/.jenkins/workspace/detox-ios-pr/detox/src/ios/expect.js
00:34:05 lerna ERR!   [2m14:error  "./earlgreyapi/GREYActions" is not found         [2mnode/no-missing-require[22m
00:34:05 lerna ERR!   [2m15:error  "./earlgreyapi/GREYInteraction" is not found     [2mnode/no-missing-require[22m
00:34:05 lerna ERR!   [2m16:error  "./earlgreyapi/GREYCondition" is not found       [2mnode/no-missing-require[22m
00:34:05 lerna ERR!   [2m17:error  "./earlgreyapi/GREYConditionDetox" is not found  [2mnode/no-missing-require[22m
00:34:05 lerna ERR!   [2m18:error  "./earlgreyapi/GREYActions+Detox" is not found   [2mnode/no-missing-require[22m
00:34:05 lerna ERR! 
00:34:05 lerna ERR! /Users/jenkins/.jenkins/workspace/detox-ios-pr/detox/src/ios/matchers.js
00:34:05 lerna ERR!   [2m2:error  "./earlgreyapi/GREYMatchers" is not found        [2mnode/no-missing-require[22m
00:34:05 lerna ERR!   [2m3:error  "./earlgreyapi/GREYMatchers+Detox" is not found  [2mnode/no-missing-require[22m
00:34:05 lerna ERR! 
00:34:05 lerna ERR! ✖ 7 problems (7 errors, 0 warnings)
```

**Comment by LeoNatan** [comment]
> (will it work on CI?)

Nope.

> 12:19:11 detox[26861] ERROR: [exec.js/SPAWN_STDERR, #87] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> 12:19:11 Selected interface does not suport video recording.

**Comment by rotemmiz** [comment]
I think we are ready to merge this to master and release a new major.
ETA, Thursday June 25th, unless something critical pops up.

**Comment by LeoNatan** [comment]
Let's keep the branch for further development.

**Comment by robto09** [comment]
Hi all!
Sorry for the inconvenience, get here after reading a medium post about Detox in 2020 (Detox Text). This version can be downloaded now?
Thanks

**Comment by rotemmiz** [comment]
detox@17.0.0

**Pull request merged**
