### PR TITLE
ci: upgrade to iPhone 12 Pro

### PR DESCRIPTION
**Pull request by noomorph**
## Description

Reaction to: https://buildkite.com/wix-mobile-oss/detox/builds/661#baf766f9-31bc-4ede-9901-eb758aeae137/1078-1143

Hopefully, it should fix the issue.

### CODE REVIEW

**Comment by noomorph** [comment]
@asafkorem  I wonder maybe it still makes sense to align the simulator version across test and example projects?

**Comment by d4vidi** [comment]
It was aligned on iPhone 11 Pro, was it not?

**Comment by d4vidi** [comment]
Sorry guys, is there a real reason for this, having already realized that the device type doesn't affect the build's stability?

**Comment by asafkorem** [comment]
Guys, I fail to reproduce the original error locally :/
I think we should close this pull request for now

**Pull request closed without merging**
