### PR TITLE
Typescript definitions

### PR DESCRIPTION
**Pull request by noomorph**
**Description:**

Initial work is done, now I just need to configure the example projects.

### CODE REVIEW

**Comment by d4vidi** [comment]
Why into `DetoxNext` and not `master`?

**Comment by noomorph** [comment]
For a historical reason, `DetoxNext` was a thing back then, but now it is the ghost of its past splendor.
I mean, back then it was not merged to master.

**Comment by d4vidi** [comment]
Well then can this be reopened as a PR to master?

**Comment by noomorph** [comment]
As soon as I finish the Jest example project migration.

**Pull request closed without merging**
