### PR TITLE
feat: expose dismissKeyboard API from EarlGrey

### PR DESCRIPTION
**Pull request by karanjthakkar**
The EarlGrey implementation has had the api to dismiss keyboard available for a very long time: https://github.com/google/EarlGrey/pull/475

This should provide an alternative for folks using detox to dismiss keyboard instead of these alternatives: [Use `by.label('Done')`](https://github.com/wix/Detox/issues/401#issuecomment-344209097), [Type `\n` in last text field](https://github.com/wix/Detox/issues/209#issuecomment-317201130 )

PS: Have been using it in our fork here: https://github.com/Skyscanner/detox/commit/e1bb5414f8766dbe5992f9f22fb280c3bb0fcdfb for a few days and it seems to be working fine 🙂 If that helps.

### CODE REVIEW

**Comment by rotemmiz** [comment]
Hey,

Thanks for the contribution!

I am wondering about this API, what is the equivalent action a user can make to dismiss a keyboard? The action imagine are: Pressing done, defocussing a text field or moving to the next line.

Also, you're missing an e2e test suite that will actually test this feature. Tell us if you need any help with it.

**Comment by LeoNatan** [comment]
I too have doubts whether such an API should exist. It is best to test by dismissing the way you expect the user to dismiss the keyboard, rather than dismissing it programatically.

**Comment by LeoNatan** [comment]
OK, let's have the option.

**Comment by LeoNatan** [comment]
One thing to see how the API behaves in the context of Detox when a keyboard is not shown and users calls the API.

**Comment by karanjthakkar** [comment]
@LeoNatan This is the error I get when I try to dismiss a hidden keyboard:

screen shot 2018-09-28 at 15 11 14

Looks good?

**Comment by LeoNatan** [comment]
Yes, looks good.

**Comment by karanjthakkar** [comment]
@LeoNatan I've added tests and updated docs. I'm not sure when the CI runs the tests for this PR but they run successfully locally. Let me know if you want me to make any more changes 🙂

**Comment by yershalom** [comment]
Hi @karanjthakkar ,
Can you please push some dummy commit to trigger the CI?

**Comment by karanjthakkar** [comment]
@yershalom done 🙂 was the failing test previously a fluke or did I miss something? 🤔

**Comment by yershalom** [comment]
If you want to set test only for specific test just add `:ios:` in the test description.
For example: https://github.com/wix/Detox/blob/master/detox/test/e2e/02.matchers.test.js#L33

**Comment by karanjthakkar** [comment]
Can someone pls check the CI? There seem to be really unrelated failures going on everytime I run it.

**Comment by rotemmiz** [comment]
I am still wondering regarding this API, as it doesn't really represent a user action, but it seems like I'm in the minority group here, so let's go ahead and add it. 
There are couple of things though I still see failing (rightfully) in CI:

1. The last test which fails on all builds, is running sanity on the creation of artifacts. Detox test suite is set to generate artifacts for every test, and if a test is added, the snapshot must be updated to include the artifacts from the new test.
2. the specific e2e test actually fails in the latest build on [RN51 iOS](https://jenkins-oss.wixpress.com/job/detox-ios-51-pr/629/console) although it passes on [RN56 iOS](https://jenkins-oss.wixpress.com/job/detox-ios-56-pr/629/console). This probably needs attention.
```
17:02:36 FAIL ./20.device-dismissKeyboard.test.js (8.58s)
17:02:36   ● Device DismissKeyboard › :ios: should dismiss keyboard
17:02:36 
17:02:36     Error: Cannot perform action due to constraint(s) failure.
17:02:36     Exception with Action: {
17:02:36       "Action Name":  "Tap",
17:02:36       "Element Description":  "<RCTUITextField:0x7fe7e9005600; AX=Y; AX.id='testInput'; AX.value='Test Input'; AX.frame={{187.66666666666666, 60}, {0, 17}}; AX.activationPoint={187.66666666666666, 68.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {0, 17}}; alpha=1; text='Test Input'>",
17:02:36       "Failed Constraint(s)":  "interactable",
17:02:36       "All Constraint(s)":  "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
17:02:36       "Recovery Suggestion":  "Adjust element properties so that it matches the failed constraint(s)."
17:02:36     }
17:02:36     
17:02:36     
17:02:36     [
17:02:36       {
17:02:36         "Description":  "Cannot perform action due to constraint(s) failure.",
17:02:36         "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
17:02:36         "Error Code":  "1",
17:02:36         "File Name":  "GREYBaseAction.m",
17:02:36         "Function Name":  "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
17:02:36         "Line":  "66"
17:02:36       }
17:02:36     ]
```

The best way of running it locally is just changing the RN version on the test project to 51 and running the e2e suite again. This script can handle this + changing to the correct react version:
`node scripts/change_react_native_version.js "detox/test" ${REACT_NATIVE_VERSION}`

**Comment by LeoNatan** [comment]
After internal discussion, this is not a direction we would like to take. Such an API encourages writing tests that diverge from actual user interaction flows. If a user should tap on the screen to dismiss, the test should be `element(by.id('background')).tap()` or pressing the return key on the keyboard.

I agree that `by.label('Done')` and typing `\n` in text fields aren't perfect, and should be improved. Would you like to discuss this and perhaps help us with a PR? I was thinking of perhaps an API such as `await element(by.id('PasswordTestId')).tapEnterKey();` or something similar that would internally type `\n` to dismiss the keyboard. What do you think?

**Comment by noomorph** [comment]
Just $0.02 from me, on Android, I think it is technically possible to dismiss keyboard as a user. Sorry for commenting into the closed thread.

**Comment by LeoNatan** [comment]
Is this standard or is it vendor dependent?

**Pull request closed without merging**
