### PR TITLE
fix(android): swipe is not working correctly on API 33-34

### PR DESCRIPTION
**Pull request by gosha212**
…pe on android 33/34

## Description

- This pull request addresses the issue described here: #4298

In this pull request, I have upgraded the version of espresso

---

> _For features/enhancements:_
 - [x] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

### CODE REVIEW

**Comment by noomorph** [comment]
@gosha212, and that was basically it, right? The Espresso was terribly outdated, do I understand correctly?

**Comment by gosha212** [comment]
> @gosha212, and that was basically it, right? The Espresso was terribly outdated, do I understand correctly?

Yes it is @noomorph. It was from 2021 and didn't support the latest versions of android. I'm sure it solved a few other issues too.

**Comment by noomorph** [comment]
@gosha212 this PR totally makes sense, but the only disturbing thing that remains is whether we need this hotfix, provided the up-to-date Espresso:

https://github.com/ericschaal/Detox/commit/f59647aefdc3d6435396a180dddb6abb0ed8d2c8

We merged this hotfix a couple of months ago, but the code there is not very intuitive. Could you advise?

**Review by noomorph — APPROVED** [review]

**Comment by gosha212** [comment]
> @gosha212 this PR totally makes sense, but the only disturbing thing that remains is whether we need this hotfix, provided the up-to-date Espresso:
> 
> [ericschaal@f59647a](https://github.com/ericschaal/Detox/commit/f59647aefdc3d6435396a180dddb6abb0ed8d2c8)
> 
> We merged this hotfix a couple of months ago, but the code there is not very intuitive. Could you advise?

Very good point! I will test it.

**Comment by gosha212** [comment]
@noomorph the fix is still needed =)

**Comment by jyotsna-hh** [comment]
What's our targeted release schedule for this? Can you quickly release this fix ?

**Comment by gosha212** [comment]
@jyotsna-hh Hopefully we will release it very soon (Today / Tomorrow)

**Comment by noomorph** [comment]
20.14.3 is out.

**Comment by jyotsna-hh** [comment]
@gosha212 @noomorph swipe is still not working with 20.14.3. I have tried the below command - 
```
 await element(by.id("keyboardScroll")).atIndex(0).swipe("up", "fast");
```

**Comment by gosha212** [comment]
@jyotsna-hh can you please open a new issue with detox and device logs? An example project would be very very helpful!

**Comment by aaronpliu** [comment]
I tested with Detox v20.14.5. Swipe is working on 33 / 34. Thanks

**Comment by sudheshbmsce** [comment]
I tried using Swipe with the latest detox version 20.14.7 and its not working for 33 / 34. I have also tried the method mentioned [here](https://github.com/wix/Detox/issues/4257#issuecomment-1859170671)

**Pull request merged**
