### PR TITLE
React Native 0.68.2 compliance

### PR DESCRIPTION
**Pull request by asafkorem**
I used RN upgrade helper: https://react-native-community.github.io/upgrade-helper/?from=0.67.2&to=0.68.2.

### CODE REVIEW

**Comment by lukaszKowal-datasite** [comment]
@asafkorem 
Do we know when Detox will support RN 0.68?
Thanks

**Comment by asafkorem** [comment]
Not yet, but we are working on it at the moment 😄

**Comment by noomorph** [comment]
I'd add that RN 0.68 compliance is top-1 in our queue at the moment. @d4vidi  is working on it 🫡

**Comment by lukaszKowal-datasite** [comment]
That is fantastic thank you Guys 🙏

**Pull request closed without merging**
