### PR TITLE
encapsulate the path in "adb.EXE devices" call

### PR DESCRIPTION
**Pull request by forki**
- [x] This is a small change 
- [x] This change has been reported in issue #1737

### CODE REVIEW

**Comment by noomorph** [comment]
Please update unit tests.

**Comment by forki** [comment]
@noomorph I'm a newcomer could you please point me to the ones that I broke?

**Comment by noomorph** [comment]
I reckon, in ADB.test.js

בתאריך יום ד׳, 6 בנוב׳ 2019, 20:35, מאת Steffen Forkmann ‏<
notifications@github.com>:

**Comment by forki** [comment]
I think the unittests are now fixed

**Pull request merged**
