### PR TITLE
feat(logger): add configuration options from CLI.

### PR DESCRIPTION
**Pull request by asafkorem**
This addresses this issue: https://github.com/wix/Detox/issues/3084, and adds an optional CLI options to configure the logger (whether to show the date, logger name, PID and metadata). 

With this change, dates will be shown by default.

For example, a standard log with the default configurations (after this change):
```
Dec 9 08:56:29 detox[1556] INFO:  Actions: should expect text fields to be focused after tap but not before [OK]
```

With `--logger-show-date false` configured:
```
detox[1556] INFO:  Actions: should expect text fields to be focused after tap but not before [OK]
```

### CODE REVIEW

**Review by noomorph — CHANGES_REQUESTED** [review]
It's not that I strongly insist, but nevertheless, I'd recommend taking it into a bit another direction:

```
DETOX_LOGGER_SHOW_DATE=true
DETOX_LOGGER_SHOW_LOGGER_NAME=true
DETOX_LOGGER_SHOW_PID=false
DETOX_LOGGER_SHOW_METADATA=false
```

That makes more sense extensibility-wise.

**Comment by asafkorem** [comment]
@noomorph you suggest also to set `DETOX_LOGGER_SHOW_PID` to be false by default?

**Comment by noomorph** [comment]
> > DETOX_LOGGER_SHOW_PID=false
> 
> @noomorph do you suggest also to set `DETOX_LOGGER_SHOW_PID` to be false by default?

I'm afraid that would be justified only in case when we are positively sure that there's only 1 worker running.

**Comment by asafkorem** [comment]
@noomorph SGTM, done.

**Comment by asafkorem** [comment]
It seems that we are not going to add this change, so I'm closing this PR.
@d4vidi @noomorph

**Pull request closed without merging**
