### PR TITLE
Add prettier for automatic code generation

### LINKED ISSUE #223: Add automatic code formatting via prettier
#### Description
In order to improve consistency in the javascript part of the code base we could add a tool like prettier to enforce automatic formatting through the code base. This would help new contributors to contribute concise code as they won't have to adapt to a certain way of formatting.

#### Plan
- [ ] add prettier formatting for the code base
- [ ] add CI check that the code base is concise 

What do you think?

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This closes #223 once it's merged. I separated the config commit from the automatic code style change commit for better readability.

### CODE REVIEW

**Comment by AlanFoster** [comment]
@DanielMSchmidt As a slightly different implementation, I've used prettier and eslint together to get great results!

The examples I can give are:

- [Adding default eslint setup](https://github.com/AlanFoster/react-examples/commit/abec9ef65e598152149dcbab09008d9a054d0674) + [Adding Prettier](https://github.com/AlanFoster/react-examples/pull/2)

This allows for devs to run `npm run lint -- --fix` to automatically fix all issues, and from your CI you can call `npm run lint` - which will exit when there's errors.

I completely stole the approach from react + react-navigation, but it works great: https://github.com/react-community/react-navigation/pull/1195/

Bonus: Wiring up husky can be awesome for pre-commit or pre-push hooks to run your linting rules, so PRs are always passing the linting rules too - [example](https://github.com/AlanFoster/react-examples/commit/386f283be80abe5ecedb33c52f75f5b3f69d9fce)

Happy to send a working PR if you'd like to see the workflow :+1:

**Comment by DanielMSchmidt** [comment]
@AlanFoster sorry for the late response. Sure, I would love to see a PR on that, thank you very much for your input and help!

**Comment by DanielMSchmidt** [comment]
Closed & waiting for @AlanFoster s PR on this topic 👍

**Comment by DanielMSchmidt** [comment]
@AlanFoster Did you have time to look into this? I think we really need this, unrelated diffs get out of hand, at least for me 🙈

**Comment by AlanFoster** [comment]
@DanielMSchmidt Yip, I was able to add new eslint config as well as prettier locally - but the end result was pretty opinionated. I'll put up a PR for the effort :+1:

**Comment by AlanFoster** [comment]
@DanielMSchmidt For visibility the main detox project already has [eslint](https://github.com/wix/detox/commit/a3e225824559b37d45e1ade27f34b2d36ed2a8b7)

The approach chosen for eslint will depend on whether or not you want to apply prettier to _all_ the code - or just the detox folder

**Comment by AlanFoster** [comment]
First PR: https://github.com/wix/detox/pull/278

**Pull request closed without merging**
