### PR TITLE
fix: device.setOrientation for iOS 16

### PR DESCRIPTION
**Pull request by mrbrentkelly**
## Description

- This pull request addresses the issue described here: https://github.com/wix/Detox/issues/3823

In this pull request, I have used the new iOS orientation APIs available from iOS 16 onwards, instead of the UIDevice orientation API's (which no longer work when building using Xcode 14 and running on iOS 16+).

_Note: I need some help/advice on how to verify these changes locally. No matter how I run it doesn't seem to be pulling in my code changes. I've tried intentionally putting compilation errors in the code and the tests still build and run without issue. I've ran `lerna bootstrap`, following by `yarn build:ios` and `yarn e2e:ios`. The tests run but don't seem to be exercising any new code._

---

> _For features/enhancements:_
 - [ ] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

### CODE REVIEW

**Comment by mrbrentkelly** [comment]
Note I believe the failing status checks are due to the fact that we are using iOS 16 APIs and therefore need to build using Xcode 14 (as opposed to 13).

**Comment by d4vidi** [comment]
@mrbrentkelly thanks for this - much appreciated! All the more so with the code seeming to have good potential. I hope @asafkorem could get around to taking a deeper look at it. In any case, Buildkite's failure is a bit obscure, and not very useful ATM. For what it's worth, I can stress out that AFAIK our CI agents do not sport xcode 14 just yet.

**Review by asafkorem — CHANGES_REQUESTED** [review]
Thanks for this contribution @mrbrentkelly, that's great! 🙌🏼 👑 

I asked our DevOps team to upgrade the Xcode on the CI agents, so the build with the new iOS 16 functionality won't fail on CI.

**Comment by asafkorem** [comment]
Sorry, I just noticed your note 🙂 

> Note: I need some help/advice on how to verify these changes locally. No matter how I run it doesn't seem to be pulling in my code changes. I've tried intentionally putting compilation errors in the code and the tests still build and run without issue. I've ran lerna bootstrap, following by yarn build:ios and yarn e2e:ios. The tests run but don't seem to be exercising any new code.

Try running `detox rebuild-framework-cache`

**Comment by asafkorem** [comment]
Our CI now has Xcode 14 (iOS 16 support), so we're finally able to continue with this PR 🙂

**Comment by AlexHayton** [comment]
This PR would be super handy for us, it's been a real blocker since adopting iOS 16. Please can it be prioritised?

**Comment by asafkorem** [comment]
@AlexHayton @mrbrentkelly sorry for the delay, I'm releasing this now. @mrbrentkelly thanks for this great contribution!

**Comment by asafkorem** [comment]
Released as [v20.2.2](https://github.com/wix/Detox/releases/tag/20.2.2) 🎉

**Pull request merged**
