### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by ferdicus**
- [x] This is a small change 
- [ ] This change has been discussed in issue #<?> and the solution has been agreed upon with maintainers.

---

**Description:**
typo `ext.detoxKotlinVerion` -> `ext.detoxKotlinVersion`

### CODE REVIEW

**Comment by LeoNatan** [comment]
Duplicate PR. CLOSING

**Comment by ferdicus** [comment]
Oh, sorry bout that - can you please link to the duplicate, I couldn't find anything.

Thanks in advance.

**Comment by d4vidi** [comment]
It's #1835

**Comment by d4vidi** [comment]
I double checked to see my memory hasn't failed me: this is _not_ a dupliate

**Comment by d4vidi** [comment]
Nevertheless, putting aside how it strikes me that this typo exists to begin with, neither this nor #1835 are sufficient. 
In any case, in order to accept this we need to:
1. Merge the minor change in #1835 
2. Apply the fix to where `detoxKotlinVersion` is set in our demo app.
3. Think through whether this is in a way a breaking change (affect only detox-Android-compiling users, probably not too many out there)

PS this is related to #1833

**Pull request closed without merging**
