### PR TITLE
Add prettier through eslint

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This is a follow up on #278, it was a bit easier to redo the changes of @AlanFoster

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@rotemmiz If there are no objections I will merge this the next days and apply prettier on this part of the repo. I will also add instruction on how to rebase other branches with the prettier changes (or do it myself if these are branches on this repo)

**Comment by AlanFoster** [comment]
@DanielMSchmidt For visibility, I had made changes to eslintrc to remove rules that actively conflicted with prettier :)

I had decided not to use `.prettierrc` to align with the eslintrc approach :)

**Comment by AlanFoster** [comment]
@DanielMSchmidt For visibility the original PR is rebased and should be good to go still :)

**Comment by DanielMSchmidt** [comment]
Awesome, lets use that one instead 👍

**Pull request closed without merging**
