### PR TITLE
doc: add cucumber integration

### PR DESCRIPTION
**Pull request by pacozaa**
## Description

- This pull request addresses the issue described here: https://github.com/wix/Detox/issues/3730

In this pull request, I have added the conclusion contained in the https://github.com/wix/Detox/issues/3730

---

> _For features/enhancements:_
 - [x] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [ ] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

### CODE REVIEW

**Comment by noomorph** [comment]
Thanks, I'll take a look after the weekend.

**Comment by noomorph** [comment]
Thanks for contributing, @pacozaa ! 😺 You unlocked an achievement:

Badge

**Comment by d4vidi** [comment]
> Thanks for contributing, @pacozaa ! 😺 You unlocked an achievement:
> 
> Badge
> 

LOL that's brilliant @noomorph ! Thanks a lot for this, @pacozaa - you've done a great job!

**Comment by d4vidi** [comment]
@pacozaa I really wish you could join our Discord so I could give you some props there for this 😄

**Comment by pacozaa** [comment]
> @pacozaa I really wish you could join our Discord so I could give you some props there for this 😄 

I am happy to! Where is your discord?

**Comment by d4vidi** [comment]
> > @pacozaa I really wish you could join our Discord so I could give you some props there for this 😄
> 
> I am happy to! Where is your discord?

You can use the discord button on our [docs page](https://wix.github.io/Detox/) 🙏🏻

**Comment by db-flutterwave** [comment]
Hi, please does anyone have a code snippet that shows how to use the code in the Cucumber integration docs? I'm quite confused about what to do with the piece of code.
Here's the doc [https://wix.github.io/Detox/docs/guide/cucumber-js-integration](https://wix.github.io/Detox/docs/guide/cucumber-js-integration)
Thanks in advance.

**Comment by pacozaa** [comment]
@db-flutterwave  Did you manage to checkout cucumber js only document first?

**Pull request merged**
