### PR TITLE
fix(android): tap event on android API>31

### PR DESCRIPTION
**Pull request by ericschaal**
## Description

- This pull request addresses the issue 3762 described here: https://github.com/wix/Detox/issues/3762

In this pull request, I have updated `obtainUpEvent` in `com.wix.detox.espresso.action.common.MotionEvent` to match more closely the implementation of `obtainUpEvent` in `androidx.test.espresso.action.MotionEvents`.

> _For features/enhancements:_
 - [x] I have added/updated the relevant references in the [documentation](https://github.com/wix/Detox/tree/master/docs) files.

> _For API changes:_
 - [x] I have made the necessary changes in the [types index](https://github.com/wix/Detox/blob/master/detox/index.d.ts) file.

### CODE REVIEW

**Comment by noomorph** [comment]
Thanks for your contribution!

Our Android guys [are currently unavailable](https://en.wikipedia.org/wiki/2023_Israel%E2%80%93Hamas_war), but I'll try to review and suggest a test plan for this PR. It might take a few days.

Could you please tell me whether this PR should work with lower Android API versions? Did you have a chance to check both `<=31` and `>31`?

**Comment by ericschaal** [comment]
> Thanks for your contribution!
> 
> Our Android guys [are currently unavailable](https://en.wikipedia.org/wiki/2023_Israel%E2%80%93Hamas_war), but I'll try to review and suggest a test plan for this PR. It might take a few days.
> 
> Could you please tell me whether this PR should work with lower Android API versions? Did you have a chance to check both `<=31` and `>31`?

My thoughts are with everyone affected by the ongoing conflicts...

Thank you for taking a look despite the circumstances. I've tested the changes on both Android API versions 34 and 29. Please let me know if there's anything else you need.

**Comment by noomorph** [comment]
Okay, I see. If you don't mind, I'll create a prerelease tomorrow (in about 14-15 hours), and let's invite volunteers to give it a try.

I'll also try to run the pre-release on our mobile projects and see how it goes.

If no complaints are detected, we'll merge that after a week of dogfooding (next Thursday, for example).

**Comment by noomorph** [comment]
The smoke version is available as [`detox@20.13.1-smoke.0`](https://www.npmjs.com/package/detox/v/20.13.1-smoke.0) on NPM.

**Comment by d4vidi** [comment]
LGTM. Thank you.

**Comment by noomorph** [comment]
✅  **The fix is available in [`detox@20.13.1`](https://github.com/wix/Detox/releases/tag/20.13.1).**

**Pull request merged**
