### PR TITLE
Debug sync will be activated on all WS calls, not only on invoke.

### PR DESCRIPTION
**Pull request by rotemmiz**
- [ ] This is a small change 
- [ ] This change has been discussed in issue #<?> and the solution has been agreed upon with maintainers.

---

**Description:**
Previously, `--debug-synchronization` was only triggered on `actions.Invoke()` commands. This PR adds support for debug sync over all slow websocket calls.
Still needs to polish over edge cases.

### CODE REVIEW

**Comment by LeoNatan** [comment]
Also consider not waiting for isReady before starting to send the sync queries. Right now there is a big limitation that it won’t print status unless the app was idle at least once.

**Comment by rotemmiz** [comment]
@LeoNatan debug sync will now be triggered on every call sent through ws, isReady is one of them. Did you mean something more than that?

**Comment by LeoNatan** [comment]
I’m not sure. I just want us to be able to debug launch sync issues.

**Comment by rotemmiz** [comment]
We got it then

**Pull request merged**
