### PR TITLE
Respect --headless option when getting emulator version

### LINKED ISSUE #2450: Issue with the --headless argument
**Describe the bug**
When running android tests in a container, `emulator -version` does not work because of missing libpulse.so.0 library. 
```
detox[5433] DEBUG: [exec.js/EXEC_CMD, #1] "/opt/android/sdk/emulator/emulator" -version
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] ""/opt/android/sdk/emulator/emulator" -version" failed with code = 127, stdout and stderr:

detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] 
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] /opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
```

This command has to be run with `-no-window` option. 
**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Install the latest detox with any runner.
2. Attempt to run `detox test --headless -l verbose`.
3. Notice in the log, that `qemu-system-x86_64` is used instead of `qemu-system-x86_64-headless`

**Expected behaviour**

The --headless command should properly work and set the -no-window argument for calling the emulator.

**Device and Verbose Detox Logs**

```
$ detox test --headless -l verbose
detox[5421] INFO:  [test.js] loglevel="verbose" headless=true useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1604495540237 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[5433] INFO:  [DetoxServer.js] server listening on localhost:40525...
detox[5433] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:40525
detox[5433] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=0e6a721c-b8c6-40ce-b426-34eece00c820
detox[5433] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=0e6a721c-b8c6-40ce-b426-34eece00c820
detox[5433] DEBUG: [exec.js/EXEC_CMD, #0] "/opt/android/sdk/emulator/emulator" -list-avds --verbose
detox[5433] DEBUG: [exec.js/EXEC_CMD, #1] "/opt/android/sdk/emulator/emulator" -version
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] ""/opt/android/sdk/emulator/emulator" -version" failed with code = 127, stdout and stderr:

detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] 
detox[5433] ERROR: [exec.js/EXEC_FAIL, #1] /opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory

detox[5433] ERROR: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Could not detect emulator binary version ChildProcessError: Command failed: "/opt/android/sdk/emulator/emulator" -version
/opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
 `"/opt/android/sdk/emulator/emulator" -version` (exited with error code 127)
    at callback (/home/circleci/unifiedpush-cookbook/react-native/push/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  code: 127,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawn],
    spawnSync: [Function: spawnSync]
  },
  stdout: '',
  stderr: '/opt/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory\n'
}
detox[5433] WARN:  [AVDValidator.js/AVD_VALIDATION] Emulator version detection failed (See previous logs)
```

**Environment (please complete the following information):**
 - Detox: 17.11.0
 - React Native: 0.63: does not matter
 - Node: v12.19.0: does not matter
 - Device: docker
 - OS: does not matter
 - Test-runner (select one): does not matter
 - Android emulator: 30.1.5.0

### PR DESCRIPTION
**Pull request by mmusil**
- [x] This is a small change 
- [ ] This change has been discussed in issue #2450 and the solution has been agreed upon with maintainers.

---

**Description:**
Resolves #2450

### CODE REVIEW

**Comment by mmusil** [comment]
Hi @noomorph, I've seen your PR #2086 and I think this is related to it. Would it be possible to have a quick look at this small PR? I would be very grateful if this could land into the next release, as it blocks my progress on automatization of RN testing.

**Comment by noomorph** [comment]
@mmusil, rozuměje se! Mnoha chvala za vašu propoziciju i za vvedeně pozornost́i do tutoho problema.

Thanks for the direct ping, I just was in the pile of other issues across a few projects. 👍 
Will take a look in a few hours.

**Comment by mmusil** [comment]
@noomorph Thank you very much for looking at this! Really appreciate it!

**Comment by noomorph** [comment]
@mmusil, how's it going? Did the fix help?

**Comment by mmusil** [comment]
@noomorph yeah, it fixed the problem :) Thanks! Now I'm figuring out some other issues :D

**Pull request merged**
