### PR TITLE
Add Android support for device.setLocation

### PR DESCRIPTION
**Pull request by clemblanco**
Everything is in PR #951.

Not sure why this has never been merged to he honest.

### CODE REVIEW

**Comment by noomorph** [comment]
Because it was flaky and never worked in a stable way.

**Comment by noomorph** [comment]
@clemblanco, try resurrecting and see if it is stable enough with the new Android emulator versions.

**Comment by LeoNatan** [comment]
The "looking for contributors" is for issues, not PRs, because it disables the stale bot. PRs should always be candidates for stale closure because of potential to get stale and be useless.

**Comment by noomorph** [comment]
@LeoNatan, my bad. I thought this is an issue, it came via notifications pane on Github.

**Comment by LeoNatan** [comment]
I worries. It probably should be, because it needs to be discussed first.

**Comment by clemblanco** [comment]
Sorry I just tried to "resurrect" that PR because trying it locally worked.

@noomorph Thanks for the `lodash` dependency I forgot along the way.

For the time being, I'm using [`androidctrl`](https://github.com/leahciMic/androidctrl) to run some `adb` command myself on my project:

```js
import AndroidCtrl from 'androidctrl';

beforeAll(async () => {
    await device.launchApp({
        permissions: { location: 'always' },
    });

   // if iOS, I use device.setLocation() from Detox, otherwise...
    await AndroidCtrl.waitForDevice(device.id);
    await AndroidCtrl.adb(device.id, 'emu geo fix -0.14176 51.50187');
});
```

But that would be nicer if this would be supported out of the box in my opinion.

I will try to get the tests passing locally and update the test artefacts too.

**Comment by LeoNatan** [comment]
Any updates here? The PR is stale. Thanks

**Comment by clemblanco** [comment]
Don't have anything to show yet. Hopefully will get some more traction soon.

**Pull request closed without merging**
