### PR TITLE
issue templates: add YAML-based issue templates.

### PR DESCRIPTION
**Pull request by asafkorem**
Add YAML-based GitHub issue templates, replacing the current issue templates.

References: 
- ["Configuring issue templates for your repository"](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).
- ["Syntax for GitHub's form schema"](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema).
> Note: GitHub's form schema is currently in beta and subject to change.

**See live example in my fork: [asafkorem/Detox->Issues->New Issue](https://github.com/asafkorem/Detox/issues/new/choose).**

### CODE REVIEW

**Review by jonathanmos — APPROVED** [review]

**Comment by asafkorem** [comment]
ping @d4vidi 🙂

**Review by d4vidi — CHANGES_REQUESTED** [review]
Android/iOS bug:
- [x] Fix description of the "In case you are experiencing a timeout in your test"
- [x] Remove auto-title
- [x] Put "What happened?" first
- [ ] "Help us reproduce this issue" - make optional? 🤔
- [ ] Remove sync debug issues 
- [ ] Test runner: add "other"?
- [ ] Logs: Can we have the user paste logs and inject the "section" tags ourselves?

**Important: Make issues flows apply proper labels**

Out of core scope but maybe do nonetheless:
- [ ] Merge the _enhancement_ input onto a single field
- [ ] Rephrase the "In case you are experiencing a timeout in your test" section to something more subtle. For example: "Try going over our synchronization troubleshooting guide".

**Comment by asafkorem** [comment]
> "Help us reproduce this issue" - make optional? 🤔

I thought about this several times, indeed this is probably the right thing.. changing 😓

**Comment by asafkorem** [comment]
> Logs: Can we have the user paste logs and inject the "section" tags ourselves?

Unfortunately it seems not, I tried 😞

**Comment by asafkorem** [comment]
Done.
Also updated my fork's main branch with these changes.

**Pull request merged**
