### PR TITLE
expose EarlGrey's matcherForInteractable

### PR DESCRIPTION
**Pull request by kkhaidukov**
Will expose EarlGrey's matcherForInteractable in `by` for iOS.

### CODE REVIEW

**Comment by kkhaidukov** [comment]
@rotemmiz I need help with this failed build here -- https://travis-ci.org/wix/detox/jobs/367176057
locally I'm not having this failure

**Comment by rotemmiz** [comment]
Travis will be Travis 😒, restarted, green

**Comment by kkhaidukov** [comment]
@rotemmiz the e2e test is added, please have another look

**Comment by rotemmiz** [comment]
I am trying to understand the usecase for using this API.
I'm trying to understand the test you added [here](https://github.com/wix/detox/pull/668/files#diff-3f98db3bae3363a915d7d36d0436bba2R71). If you're just trying to test that the view can be interacted upon, why not use expect to be visible ? it may be even more conservative since it has 75% visibility threshold.
BTW, EarlGrey validates on most actions if the view is intractable before performing, tap included, so the test you wrote seems redundant.

**Comment by kkhaidukov** [comment]
@rotemmiz We have an app with tabbed interface, and two (or more) tabs may have elements with the same testIDs, because when the tab is switched, a new screen is pushed onto the stack, overlaying the one beneath it (which is not destroyed and its elements are therefore locatable). In this case, detox cannot distinguish between the two elements when trying to e.g. tap.

Adding the `interactable` matcher solves this problem -- if I remove `.and(by.interactable())` from my test, it will fail because multiple elements are matched.

**Comment by rotemmiz** [comment]
What prevents you from adding testID to each tab ?

**Comment by rotemmiz** [comment]
`interactable` means that this view has 10 at least visible pixels. does this solve your issue ? how ?

BTW, I think [this proposition](https://github.com/wix/detox/issues/251) will solve your problem and much more.

**Comment by kkhaidukov** [comment]
> What prevents you from adding testID to each tab ?
would that help? `withAncestor` still matches only immediate parents, or am I doing something wrong

> does this solve your issue ? how ?
it does, it ensures that only the elements belonging to the uppermost screen will be matched

> BTW, I think this proposition will solve your problem and much more.
it might, but it doesn't look like it's getting any action

**Comment by rotemmiz** [comment]
So is everything mounted to the screen (even things which are not in the active tab?)
Do you use react native navigation?

**Comment by kkhaidukov** [comment]
> So is everything mounted to the screen (even things which are not in the active tab?)

yes

> Do you use react native navigation?

if you mean `wix/react-native-navigation`, then no, we don't

**Comment by rotemmiz** [comment]
In sake of your app's performance, try detaching those views from the hierarchy. This will also solve your problem.

**Comment by kkhaidukov** [comment]
@rotemmiz any other changes needed to get this PR merged?

**Comment by rotemmiz** [comment]
Hey, sorry for the delayed response here, but I don't think this PR is a good idea, along with what I wrote previously. 
A solution that can solve your problems (and was already kinda [implemented on Android](https://github.com/wix/detox/commit/b9a832f665606f130a37c7d924c6cfc5ef014e41)), is making sure non-interactable views won't be matched. 

A PR of this type makes much more sense IMO.

**Comment by rotemmiz** [comment]
Detox is being used in React Native Navigation v2, and we had the same issue of multiple views with the same testID on multiple tabs on its  Android playground app (the app we test RNNv2 on).
Adding the same functionality on iOS matchers should be added here: https://github.com/wix/detox/blob/master/detox/ios/Detox/GREYMatchers+Detox.m

You'll probably need to add `matcherForInteractable` to `grey_allOf()` on all matchers.

**Comment by kkhaidukov** [comment]
Currently I'm trying to switch IdMatcher from calling GreyMatchers.matcherForAccessibilityID to a method that I created in GREYMatchers+Detox.m that looks like this:
```
+ (id<GREYMatcher>)detoxMatcherForAccessibilityID:(NSString *)accessibilityID {
    if (![ReactNativeSupport isReactNativeApp])
    {
        return  [self matcherForAccessibilityID:accessibilityID];
    }
    else
    {
        Class RCTTextViewClass = NSClassFromString(@"RCTText") ?: NSClassFromString(@"RCTTextView");
        return grey_allOf(grey_sufficientlyVisible(),
                          grey_accessibilityID(accessibilityID),
                          grey_not(grey_descendant(grey_allOf(grey_kindOfClass(RCTTextViewClass),
                                                              grey_accessibilityID(accessibilityID),
                                                              nil))),
                          nil);
    }    
}
```
But the problem is, the tests get very noticeably slower, when there is an extra grey_ matcher inside of grey_allOf. I've tried with `grey_sufficientlyVisible` and `grey_interactable`.
Is it the expected behavior or am I just doing it wrong?
@rotemmiz @LeoNatan

**Pull request closed without merging**
