### PR TITLE
feat(timeline artifact): add invoke timeline events.

### PR DESCRIPTION
**Pull request by asafkorem**
Add started and ended events for invoke (client actions) in the timeline artifact. @jonathanmos

### CODE REVIEW

**Comment by asafkorem** [comment]
This code needs

**Comment by d4vidi** [comment]
Not needed?

**Comment by asafkorem** [comment]
> Not needed?

Definitely needed. The PR is irrelevant for now.
We're making some changes to the implementation.

**Comment by asafkorem** [comment]
The PR was closed to avoid redundant reviews 😅

**Pull request closed without merging**
