### PR TITLE
Add example for GitHub Actions

### PR DESCRIPTION
**Pull request by alexsegura**
- [x] This is a small change 
- [ ] This change has been discussed in issue #<?> and the solution has been agreed upon with maintainers.

---

**Description:**

This adds an example workflow to run Detox on iOS with GitHub Actions.
I can also provide an example for Android with [android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner), but I never managed to run it successfully.

### CODE REVIEW

**Comment by rotemmiz** [comment]
Great, thanks for this example. We wanted to give it a try and move Detox to github actions as well, this will surely help.
Regarding Android, I heard that some had a successful android e2e with Github Actions (though I am very doubtful after bad experience with Circle CI, Travis CI and bitrise handling x86 Emulators).
We have an issue open about that (re)opened about that
https://github.com/wix/Detox/issues/1761

and here's the gist of someone who managed to run Detox with Android Emulators on Github Actions:
https://gist.github.com/edvinasbartkus/4c09d85ac6f2a2f9eec9d9c8deac5e61

**Comment by alexsegura** [comment]
I have an open pull request on my app if you want to take a look coopcycle/coopcycle-app#414

The emulator seems to start, but the app never finishes starting. Check the logs of my builds. 
I had to manually write `hw.lcd.width`/`hw.lcd.height` in AVD's `config.ini` to make it start (see #1504). 
Also, I had some troubles with Proguard, I disabled it.

**Comment by d4vidi** [comment]
@alexsegura thanks a lot for this! seems that in your CI the emulators fail to load. I think it'd be best to hold this PR until we have a truly working example, or we'd be giving a false impression of that detox (Android) works well on Github actions.

**Comment by alexsegura** [comment]
@rotemmiz @d4vidi finally got it working 🙂 

The main problem was related to [clear text traffic disabled](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#problem-the-app-loads-but-tests-fail-to-start-in-sdk--28) on API Level > 27.

I think it's possible to use a `network_security_config.xml`, but I haven't found how to enable it only for release builds created for Detox. In the meantime, I added a step with this a quick'n'dirty patch:

```
brew install xmlstarlet
xmlstarlet ed --inplace --ps --insert "/manifest/application" --type attr -n "android:usesCleartextTraffic" -v "true" android/app/src/main/AndroidManifest.xml
```

Also, as the `reactivecircus/android-emulator-runner` action takes care of creating & spinning an emulator, I use `emulator-5554` as the device name.

**Comment by d4vidi** [comment]
@alexsegura just to be sure I got it right... you're using an attached device but it's name is `emulator-5554`?

**Comment by alexsegura** [comment]
@d4vidi exactly. As I rely on [reactivecircus/android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner) for the painful work of launching an emulator properly, I'm using the emulator it creates. 

I think using ready-made actions is totally in the philosophy of GitHub Actions, we should avoid writing code to launch the emulator. Instead, if we find limitations, we should contribute to the already-existing action 😉 
> An action is a reusable unit of code.

**Comment by d4vidi** [comment]
@alexsegura traditionally, Detox works best when managing (and launching) the emulators on its own, and it can (should) also handle attached devices. Have you considered using Detox for this?

**Comment by alexsegura** [comment]
Ok, I will test directly with Detox.

**Pull request closed without merging**
