### PR TITLE
set location should not use comma

### PR DESCRIPTION
**Pull request by hiaw**
using comma instead of dot will cause fbsimctl to fail.

### CODE REVIEW

**Comment by rotemmiz** [comment]
CI should be green now, can you please rebase the PR and rerun the tests ?

**Comment by LeoNatan** [comment]
Can you please explain what is going on here? What the issue is and what the fix is? I don't understand.

**Comment by hiaw** [comment]
The current code will give error if giving geo coordinate with decimal points. The PR should fix it.

screen shot 2018-01-29 at 1 16 07 pm
screen shot 2018-01-29 at 1 16 30 pm

**Comment by hiaw** [comment]
@rotemmiz this PR is rebased to the master branch. 

But CI will fail because the test project's detox based on the  npm version instead of building from this code change.

https://github.com/wix/detox/blob/master/detox/test/package.json#L19

**Comment by rotemmiz** [comment]
Why do you suspect it uses the npm version?
We use lerna to control the project dependencies. Projects in the monorepo which are declared in lerna.json are being linked inside node_modules rather than being downloaded from npm.

**Comment by hiaw** [comment]
ok. i'm not correct. 

The CI failed because of wrong username & password while trying to publish the doc? 
https://travis-ci.org/wix/detox/jobs/334522771

**Comment by rotemmiz** [comment]
@DanielMSchmidt can you please help with this?

**Comment by DanielMSchmidt** [comment]
@rotemmiz two fixes, one is in #544 so it doesn't even run for the PR.
The second one is we (someone with full access to travis 😉 ) need to set `$GIT_USER` and `$GIT_TOKEN` with valid credentials that allow a push to the repo (for the github-pages branch). For more details, [please see the documentation of Docusaurus](https://docusaurus.io/docs/en/publishing.html)

**Comment by rotemmiz** [comment]
Hi again, 
Please rebase your branch so we can make sure tests pass.

**Comment by hiaw** [comment]
ok. done. no conflict & all test passed

**Comment by LeoNatan** [comment]
Thanks, merged

**Pull request merged**
