### PR TITLE
iOS 13 Support

### LINKED ISSUE #1637: iOS 13 Support
I am currently unable to run Detox on iOS 13. It all works as expected if I assign a simulator with iOS 12.X. However, the app crashes with a `Signal 11` error that I am having a hard time tracing. 

Has anyone here tested Detox on iOS 13? Is it confirmed to be compatible?

### PR DESCRIPTION
**Pull request by LeoNatan**
Will wait for iOS 13 CI before merging. Xcode 11 should be released in a ~ week.

Closes #1637

### CODE REVIEW

**Comment by LeoNatan** [comment]
@d4vidi Android failed. Can you please check if it's related to parallel?

**Comment by d4vidi** [comment]
So weird... a simple tap ended up becoming a long tap, which created a chain of failures. While a possible bug, it cannot be related to changes made purely for iOS.

**Comment by LeoNatan** [comment]
This PR is pending Xcode 11 upgrade in our OSS CI machines. Hopefully, this should happen in the next few days. CC @igorgn @rotemmiz

**Comment by reneeichhorn** [comment]
Anyone else having issues with the visibility matcher within this branch? They seem to fail for me in especially when element is in an modal.

Xcode 11 + iPad OS 13 => failing
Xcode 10.1 + iOS 12.x => successful

I guess if its indeed a bug it would be on Earlgrey side right?

**Comment by LeoNatan** [comment]
Could you please create a small sample project reproducing this issue?

**Comment by SMJ93** [comment]
Hey @LeoNatan, can we release this?

**Comment by LeoNatan** [comment]
We are having some troubles with our CI. Once those are sorted, of course.

**Comment by LeoNatan** [comment]
@SMJ93 14.3.4 out with iOS 13 support. Please test and let me know if you have issues.

**Comment by SMJ93** [comment]
Thanks @LeoNatan, will test now

**Comment by LeoNatan** [comment]
Fantastic, thanks for letting us know!

**Pull request merged**
