### PR TITLE
feat: new device allocation lifecycle

### LINKED ISSUE #2894: Fix cleanup in multi-worker envs (DAS project)
## Description

**DAS** = **D**evice **A**llocation **S**erver

A rearchitecture of Detox' device allocation concern. In a nutshell - we want to have that concern either implemented as a global-scope managed server, or integrated into the existing Detox-server itself*.

The issue address the **1st phase** in what could be an inception of further future improvements. It's scope is (roughly):
- [x] Make existing Detox server managed at global scope (rather than having distinct servers bootstrapped and killed over and over again based on workers' lifecycles).
- [x] Setting up this kind of a server at global-scope (either as an independent entity, or bundled into the existing Detox server). It will strictly be running at local host, for the time being, so as to avoid adding this up into a bigger, hard-to-manage change.
- [x] De-facto activating the server...

(@noomorph this is what I had in mind, obviously you're the one to decide the best way to move forward!)

### LINKED ISSUE #3573: [Epic] DAS Phase 1: Global device allocation
### Description

When using the `android.genycloud` device type, it is not possible to run multiple `detox test …` commands in parallel like that:

```bash
detox test -c android.geny.release -n Recipe1 & \ # session.id = e54490fd-7cb7-e05a-586e-c3ec23540496
detox test -c android.geny.release -n Recipe2 & \ # session.id = 1acee489-e9d3-4a82-8e50-24f723f60ff8
wait
```

The problem is that the fastest command would go over the `~/Library/Detox/genycloud-cleanup.lock`, e.g.:

```json
[
  {"id":"d9d09cbf-df0b-4044-ae07-32d794a65d49","data":{"name":"Detox.e54490fd-7cb7-e05a-586e-c3ec23540496.w1"}},
  {"id":"39178451-9b6f-43b9-9053-7321294255ab","data":{"name":"Detox.1acee489-e9d3-4a82-8e50-24f723f60ff8.w1"}},
]
```

and stop all the instances, including the ones that do not belong to its test session.

In this example, if the session `e54490fd-7cb7-e05a-586e-c3ec23540496` completes faster and cleans up, then the slower one,`1acee489-e9d3-4a82-8e50-24f723f60ff8`, will start failing after this, because its device will have been stopped by that moment.

### Suggested solution

Move the device allocation to the primary (global) context and stop using lock files in the Genymotion SaaS drivers. The global allocation mechanism will track all the devices created throughout the test session, but since it will be happening in memory, there will no longer be a shared file to fight over. Voila! No file – no problem.

### Gameplan

```[tasklist]
- [ ] #3655
- [ ] #2106
- [x] #2894 (`--u, --cleanup` works incorrectly in Jest (devices are being shut down after each test suite)
- [x] Race conditions when running multiple "detox test ..." commands in parallel
```

### LINKED ISSUE #3655: [Genymotion SaaS] Device name conflict after environment setup timeout
### What happened?

There were two tests: `test1` and `test2`.

Detox started a Genymotion SaaS device for `test1`. The environment setup failed with a timeout.

Then we switched to `test2`. Detox tried to allocate a device with the same name and failed, because Genymotion SaaS does not allow to create devices with the same name.

### What was the expected behaviour?

Perhaps, Detox should have destroyed the first device if there were some problems with it.

Then the second test would have created a device with the same name again without any problem.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

_No response_

### In what environment did this happen?

Detox version: 20.x.x
Test-runner (select one): jest-circus

### Detox logs

_No response_

### Device logs

_No response_

### More data, please!

image

### PR DESCRIPTION
**Pull request by noomorph**
Resolves #2894.
Resolves #3573.
Resolves #3655.

- [ ] #3573
- [ ] #3655
- [ ] #2894 (`--u, --cleanup` works incorrectly in Jest (devices are being shut down after each test suite)

Enabler for:

- [ ] #1331 (likely, the Android-specific PR won't be very needed after that: #3497 )

## Description

1. Device allocation now happens in the Detox primary context (the top parent process). That allows storing all the allocation data and history in memory and opens many technical possibilities. The Detox worker (via the secondary context) sends IPC commands to allocate and deallocate a device respectively.
2. Device allocator drivers now have `init`, `cleanup` and `emergencyCleanup` methods for the global lifecycle handling. 
3. Device registry (lock file wrapper) can register a device, release a device (without unregistering it), and unregister it completely. Every device is associated with Detox test session id to prevent stealing from a concurrent Detox run.
4. Genymotion SaaS allocation driver keeps track of all the allocated devices in memory, making it impossible to cause conflicting lock file resets. It is not limited to one device per worker - if device allocation fails, the worker can retry and allocate one more device.
5.  Limited `deviceShutdown` event only to `device.resetContentAndSettings()` on iOS for the artifacts manager. Also, `bootDevice` event is now synthetic - used only to make sure that the artifacts manager knows a correct device id. 
6. Minor refactors in the utility classes.

### CODE REVIEW

**Comment by d4vidi** [comment]
@noomorph I've switched to tracking these tasks under #3573, which is an issue rather than a PR.

**Comment by d4vidi** [comment]
Is #2106 in fact necessary here? Is it necessary at all? It used to address issues with local emulators running on Linuxes and I don't think it's of high interest anymore.

**Comment by noomorph** [comment]
@d4vidi #2106 was cheap enough to implement, and I believe it has positive impact on community.

**Comment by noomorph** [comment]
Merged via 9bb74739f1fbdcdf6678926fccfb806c50b2c8a7.

**Pull request closed without merging**
