### PR TITLE
New demo project for react native jest

### PR DESCRIPTION
**Pull request by SMJ93**
I've created a new up to date demo project for react native which uses jest as a test runner.

This should help with debugging the jest test runner as it doesn't work for iOS or Android at the moment.

To run:

```
cd examples/demo-react-native-jest
yarn
npm run test-android
npm run test-ios
```

### CODE REVIEW

**Comment by SMJ93** [comment]
Closed as this is included with https://github.com/wix/detox/pull/371

**Comment by SMJ93** [comment]
@Kureev Here is the demo project without the Jest test runner fix

**Comment by Kureev** [comment]
Is it blocked by #371?

**Comment by SMJ93** [comment]
@kureev yep, it's set up to use the fixed jest test runner in #370.

**Comment by sibelius** [comment]
this is great

**Comment by sibelius** [comment]
I think this project example is great https://github.com/mfrachet/detox-example

**Comment by rotemmiz** [comment]
@SMJ93 , note 2 I wrote in #371 probably applies here.
What do you say about adding a new build flavor in our matrix and add the demo projects, including this one ? I can help setting it up if you need any help.

**Comment by SMJ93** [comment]
@rotemmiz  Yeah, that makes sense. I still think it is useful having an example for Jest separate to the build flavor in the matrix. It's helpful for people starting out with detox and maintaining the Jest test runner.

**Pull request merged**
