### PR TITLE
add -f option to run specific test file

### PR DESCRIPTION
**Pull request by jeremyeaton89**
Hey guys,

I've been using this flag with glee. Wondering if you guys think it'd be a good idea.

cheers

PS great job with the project!

### CODE REVIEW

**Comment by jeremyeaton89** [comment]
Decided to do this vs finagling with jest when i do a `detox test`

**Comment by jeremyeaton89** [comment]
#RunnerAgnostic

**Comment by Cederman** [comment]
This PR should be ready to merge.

**Comment by jeremyeaton89** [comment]
nuked my last fork. Reopened PR here: https://github.com/wix/detox/pull/616

**Pull request closed without merging**
