### PR TITLE
fixing #1728

### PR DESCRIPTION
**Pull request by matejdr**
- [x] This is a small change 
- [ ] This change has been discussed in issue #1728  and the solution has been agreed upon with maintainers.

---

This is a small change.

Debug trace of the error:

11-18 17:59:07.916  6755  6964 E DetoxManager: Exception
11-18 17:59:07.916  6755  6964 E DetoxManager: java.lang.reflect.InvocationTargetException
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at java.lang.reflect.Method.invoke(Native Method)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:443)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:405)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.invoke.types.ClassTarget.execute(ClassTarget.java:23)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.invoke.types.Target.invoke(Target.java:59)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:35)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.detox.InvokeActionHandler.handle(DetoxActionHandlers.kt:49)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.detox.DetoxManager$2.run(DetoxManager.java:105)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at android.os.Handler.handleCallback(Handler.java:873)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at android.os.Looper.loop(Looper.java:193)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.detox.Detox$1.run(Detox.java:134)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at java.lang.Thread.run(Thread.java:764)
11-18 17:59:07.916  6755  6964 E DetoxManager: Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.detox.Detox.launchActivitySync(Detox.java:219)
11-18 17:59:07.916  6755  6964 E DetoxManager: 	at com.wix.detox.Detox.startActivityFromUrl(Detox.java:148)

Do you have a test for this maybe where I could see it working?

### CODE REVIEW

**Comment by rotemmiz** [comment]
Hey there! Thanks for this PR.
According to your scenario in your issue, you want to launch the app/activity with the same instance (newInstance: false). Adding those intent flags so the opposite, I'm not sure this is the right solution.
We want to be able to mock opening a deep link when the application is in background (we have an e2e test for that)

**Comment by d4vidi** [comment]
@matejdr in essence all tests are green and we _do_ test this use case so you should be good. Nevertheless this is a delicate area and specifying these flags consistently is something I'll have to take a deeper look into.

**Comment by matejdr** [comment]
I get it guys, you are super careful. I used this approach with Appboy, when having the same issue on android.
But can you point me out in the right direction on how can I run your e2e test for deep linking when the app is in the background?

**Comment by d4vidi** [comment]
@matejdr I appreciate your time, but nevertheless have to close this in favor of #1794.

**Comment by matejdr** [comment]
no worries, thanks for fixing it

**Pull request closed without merging**
