### PR TITLE
Create a build matrix to support multiple version of React Native and OSs

### PR DESCRIPTION
**Pull request by rotemmiz**
The end goal is to run a build matrix to support the following:
- Multiple versions of React Native (latest and the version used internally at Wix)
- Multiple versions of Xcode (currently 8.3.3 and 9, 8.3.3 will be dropped soon)
- Add Android test suite to CI, including E2E and device control tests, on multiple OS versions, and preferably on Linux.

The current PR resolves the first two points.
Of course, a lot of CI Driven Development had to be done in order to understand what is supported in TravisCI and what's not (Hence CIDD commits)

### CODE REVIEW

**Comment by LeoNatan** [comment]
I’d close this PR, it’s not written in … <details> 
  <summary>TDD</summary>
   <p>Travis Driven Development</p> 
</details>

**Comment by rotemmiz** [comment]
Travis Driven Development is a kind of TDD

**Comment by DanielMSchmidt** [comment]
Would it make sense for the next time to squash the commits and provide a meaningful commit message? It feels to me like git blame / history might be a problem for the files involved 😇  Just my humble opinion, no offence 👍 But great job, I hope we will spot a lot of errors with this 👍

**Comment by rotemmiz** [comment]
Dear Mr. @DanielMSchmidt,
Every PR we accept is squashed before being merged to master, this one included.

**Comment by DanielMSchmidt** [comment]
Ups, sorry, I didn't knew that and I must have missed this here :/ sorry to be the one writing incorrect and annoying comments :(

**Pull request merged**
