### PR TITLE
Detox cucumber integration guide

### PR DESCRIPTION
**Pull request by mathanpec**
- [x] This is a small change 
- [x] This change has been discussed in issue #<?> and the solution has been agreed upon with maintainers.

---

**Description:**
This PR adds a guide to documentation on steps to integrate cucumber with Detox

### CODE REVIEW

**Comment by LeoNatan** [comment]
Hello,
Thanks, but this guide should really sit in the repo you created, and we should just link to it in Detox docs. As said before, we don't have the capacity to support such guides.
Thanks

**Comment by mathanpec** [comment]
Hi @LeoNatan,

Thanks, I have moved the details in the guide to my example repo itself and now just linking my example repo here.

I have still kept the link under `Guides` section. Let me know if it is fine or should it be moved to some other section like `External Links`.

**Comment by mathanpec** [comment]
Hi @LeoNatan,

Can you help here? I am not exactly sure why test cases are failing for this change.

**Comment by LeoNatan** [comment]
No worries about the CI. Thanks!

**Pull request merged**
