### PR TITLE
Add aar support

### PR DESCRIPTION
**Pull request by DanielZlotin**
…ot of shenanigans is required

### CODE REVIEW

**Comment by DanielZlotin** [comment]
Usage: `gradle clean publish`

**Comment by d4vidi** [comment]
❗️*IMPORTANT* Note to self/implementor: When introducing `.aar` files, need to make sure detox lib proguard rules are bundled and that are declared using `consumerProguardFiles 'proguard-rules.pro'` in the `android{} > defaultConfig{}` section of the gradle build files.

**Comment by d4vidi** [comment]
This PR is out of date. I'll open a new one when ready with the actual implementation. Closing for now.

**Comment by rotemmiz** [comment]
🤯

**Pull request closed without merging**
